name: Update @tajawal/web-docs-cli on dependent repos

on:
  push:
    branches: [master]

jobs:
  update-web-docs-cli:
    name: Update @tajawal/web-docs-cli on dependent repos
    runs-on: ubuntu-latest

    steps:
      - name: Dump context
        run: echo '${{ toJSON(github.event.commits[0]) }}'
      
